package com.estudo.megasema.configuration.exception;

import jakarta.servlet.http.HttpServletRequest;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.server.MethodNotAllowedException;

import java.util.Map;

@ControllerAdvice
@Slf4j
public class ExceptionHandlerConfiguration {

    @ExceptionHandler({Exception.class})
    public ResponseEntity<Map<String, Object>> badRequestHandler(HttpServletRequest request, Exception e) {
        log.warn("{}. Bad request generated by exception: \n\t{}", request.getServletPath(), e.getLocalizedMessage());
        return ExceptionResponse.from(e).setPath(String.valueOf(request)).setStatus(HttpStatus.BAD_REQUEST).build();
    }

    @ExceptionHandler({MethodNotAllowedException.class})
    public ResponseEntity<Map<String, Object>>methodNotAllowedHandler(HttpServletRequest request, Exception e) {
        log.warn("{}. Bad request generated by exception: \n\t{}", request.getServletPath(), e.getLocalizedMessage());
        return ExceptionResponse.from(e).setPath(String.valueOf(request)).setStatus(HttpStatus.BAD_REQUEST).build();
    }


}
