
name: CI- enviar imagem para o DockerHub

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
            
  CRIAR-NOVA-IMAGEM:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Autenticando usuário no docker
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Verificando a definição de GITHUB_REF
        env:
          IMAGE_TAG: "${GITHUB_REF##*/}"
        run: echo "O valor de GITHUB_REF é ${{ env.IMAGE_TAG }} " |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      
      - name: Construindo a imagem e enviando para o DockerHub
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./Dockerfile
          context: ./
          push: true
          tags:  |
            viniciushora/megasena:latest
            viniciushora/megasena:${{ env.BRANCH }}
            
            
            
            
            
